### ISSUE TITLE
Root for different tab

### ISSUE THREAD

**Issue by sphynx79** [szw/vim-ctrlspace#144]
Please someone can tell me, how i can set different root for every tab.

thanks.

**Comment by szw** [comment]
It's not possible. The root is only one and global. You can however switch to different roots often by pressing `<i>` and `<I>` (switch root the the directory of selected file).

**Comment by sphynx79** [comment]
I found the solution i use lcd for set local root for every tab.

Thanks

2015-09-19 16:35 GMT+02:00 Szymon Wrozynski <notifications@github.com>:

**Comment by szw** [comment]
Well, technically it's a possible although not supported and not advised solution. The plugin would override your custom local roots if you try to set a root from bookmarks, or use aforementioned `<i>` and `<I>` keys. Or even if you try to move/rename a file. Also your local roots won't be included in the workspace.

Honestly I've found local roots quite annoying also because the Go plugin I use seems to set them all the time internally. Therefore I put a lot of effort to overcome and diminish their impact on plugin behavior. And of course that would make your approach a bit more challenging ;). Anyways, be warned you shouldn't really rely on local roots while using Vim-CtrlSpace.
